class GeneticConfig:
    GENOME_LENGTH = 500
    POPULATION_SIZE = 20
    MAX_GENERATIONS = 2500
    NUM_ISLANDS = 4
    NUM_EXPERIMENTS = 10

    # Learning parameters
    LEARNING_RATE = 0.9
    EXPLORATION_RATE = 0.01
    BATCH_SIZE = 4
